### ISSUE TITLE
Missing "tmpdir" option in downloads

### ISSUE THREAD

**Issue by LattaruoloAndrea** [CDSETool/CDSETool#149]
## Describe the bug
As discussed in #51 there should have been a parameter in order to specify the temporary directory. Did the support to this feature change or it's not supported anymore?

the current version seems like it creates a temporary file (inside download.py)
```python
                with tempfile.NamedTemporaryFile() as file:
                    # Server might not send all bytes specified by the
                    # Content-Length header before closing connection.
                    # Log as a warning and try again.
                    try:
                        for chunk in response.iter_content(chunk_size=1024 * 1024 * 5):
```

### Expected behavior
```python
list(
    download_features(
        features,
        PATH_WHERE_TO_SAVE,
        {
            "tmpdir": PATH_WHERE_TO_SAVE, ##this not supported?
            "concurrency": 4,
            "monitor": StatusMonitor(),
            "credentials": Credentials(USER_SENTINEL_ESA, PASSWORD_SENTINEL_ESA),
        },
    )
)
```
the tempdir looks like it's not supported anymore.

### Environment
 - OS: Ubuntu 23.10
 - Package version: [cdsetool==0.2.11]
 - Python version: [3.11.6]

**Comment by pedep** [comment]
There was a change to the tmpdir option in https://github.com/CDSETool/CDSETool/pull/124, which may the issues you are experiencing. As you note, a fix is proposed in #51 (and https://github.com/CDSETool/CDSETool/issues/132), which is still in the feature request stage

I will try to prioritize this feature, as i imagine users downloading cross-filesystem might experience highly reduced IO

**Comment by LattaruoloAndrea** [comment]
Perfect. I thought it was already available and for some reason it was not available anymore. Then I shell wait.
Thanks

**Comment by pedep** [comment]
i will notify you in #51 when the feature has been released :+1:

**Comment by LattaruoloAndrea** [comment]
Hello any news on the feature #51?
