### ISSUE TITLE
Download on WINDOWS OS fails

### ISSUE THREAD

**Issue by LattaruoloAndrea** [CDSETool/CDSETool#150]
## Describe the bug
Hello, I tried to run the simple code and test it on  two different windows machines and I had the same error. Basically there is a permission denied, once the script tries to read from the temporary directory to copy the  downloaded file. (I used the shell with administrative privileges)
```
Traceback (most recent call last):
  File "C:\Users\geouser\test_sentinel\test_sentinel_lib_no_proxy.py", line 24, in <module>
    list(
  File "C:\Users\geouser\test_sentinel\env\Lib\site-packages\cdsetool\download.py", line 114, in download_features
    yield from _concurrent_process(
  File "C:\Users\geouser\test_sentinel\env\Lib\site-packages\cdsetool\_processing.py", line 61, in _concurrent_process
    yield future.result()
          ^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\ProgramData\miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\geouser\test_sentinel\env\Lib\site-packages\cdsetool\download.py", line 112, in _download_feature
    return download_feature(feature, path, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\geouser\test_sentinel\env\Lib\site-packages\cdsetool\download.py", line 88, in download_feature
    shutil.copy(file.name, result_path)
  File "C:\ProgramData\miniconda3\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\miniconda3\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\LOCAL_~1\\Temp\\tmp8zf1spgi'
``` 

### Steps to reproduce
My code is as follow:

```python
from cdsetool.query import query_features
from cdsetool.credentials import Credentials
from cdsetool.download import download_features
from cdsetool.monitor import StatusMonitor
from datetime import date

PASSWORD_SENTINEL_ESA = "" 
USER_SENTINEL_ESA = ""
PATH_WHERE_TO_SAVE = "path"
features = query_features(
    "Sentinel1",
    {
        "startDate": "2023-12-29",
        "completionDate": date(2024, 1, 4),
        "processingLevel": "LEVEL1",
        "sensorMode": "IW",
        "productType": "IW_GRDH_1S",
        "geometry": "POLYGON((4.220581 50.958859,4.521264 50.953236,4.545977 50.906064,4.541858 50.802029,4.489685 50.763825,4.23843 50.767734,4.192435 50.806369,4.189689 50.907363,4.220581 50.958859))"
    },
)

list(
    download_features(
        features,
        PATH_WHERE_TO_SAVE,
        {
            "concurrency": 4,
            "monitor": StatusMonitor(),
            "credentials": Credentials(USER_SENTINEL_ESA, PASSWORD_SENTINEL_ESA),
        },
    )
)

```

### Expected behavior
I guess this should be fixed with the #51 where we can change the temp dict. But still I guess this behavior should not be possible even using the temp directory.

### Environment

-------------------------------------------- System 1 --------------------------------------------
 - OS: [windows 10]
 - Package version: [cdsetool==0.2.11]
 - Python version: [ 3.11.3]
 - Other details that you think may affect. The shell terminal was executed in administrator mode
-------------------------------------------- System 2 --------------------------------------------
 - OS: [windows 11]
 - Package version: [cdsetool==0.2.11]
 - Python version: [ 3.11.3]
 - Virtual machine with windows. The shell terminal was executed in administrator mode

**Comment by LattaruoloAndrea** [comment]
Hello does anyone was able to reproduce or tested the issue so far?

**Comment by eikeschuett** [comment]
I get exactly the same behavior on Windows 10 with cdsetool 0.2.11 and Python 3.12.4.

**Comment by LattaruoloAndrea** [comment]
@eikeschuett Good that I am not the only one.

**Comment by scotjohn** [comment]
Same problem here.

**Comment by pjonsson** [comment]
I don't have Windows, but I'm guessing the shell with administrative privileges runs CDSETool as the administrator.

Unless it's absolutely necessary, I would advise against running anything that talks with remote systems as administrator since there has been a steady stream of security vulnerabilities relating to unexpected responses/inputs for the past 30+ years. Running as a regular user doesn't eliminate security issues but it limits the blast radius, so even if something bad were to happen, the system will still boot and you can restore a backup of the user's files.

**Comment by LattaruoloAndrea** [comment]
But the problem is present even if you run a shell without  administrative privilege, so I guess it was not a problem of shells executions but more of code and how windows interpret that code in the OS I guess not sure here.
From what I understood yesterday from debugging on windows I found out this
```python
                with tempfile.NamedTemporaryFile() as file:
                    # Server might not send all bytes specified by the
                    # Content-Length header before closing connection.
                    # Log as a warning and try again.
                    ...
                    shutil.copyfile(file.name, result_path)
```
At first there is this piece of code in which the tempfile is created and all the data is saved inside the stream, the problem rise on the `shitil.copyfile(...)`, from what I understood inside the `with ... file:` the file is open in write mode, and since it' open in this mode the copyfile needs to read from the file but in windows specifically rise a permission error since it was open in write mode and not in read mode. That's why I tried to test things around and came up with copying the file outside the `with ... file:  ` which I implemented in #168.
```python
                with tempfile.NamedTemporaryFile(
                    dir=temp_dir, prefix=filename_prefix, delete=False
                ) as file:
                    # Server might not send all bytes specified by the
                    # Content-Length header before closing connection.
                    # Log as a warning and try again.
                    filename_temp_created = file.name
                    try:
                        for chunk in response.iter_content(chunk_size=1024 * 1024 * 5):
                            file.write(chunk)
                            status.add_progress(len(chunk))
                    except (
                        ChunkedEncodingError,
                        ConnectionResetError,
                        ProtocolError,
                    ) as e:
                        log.warning(e)
                        file.close()
                        os.unlink(filename_temp_created)
                        filename_temp_created = None
                        continue
                    file.close()
                if filename_temp_created is not None:
                    # copying here allows windows to work
                    shutil.copyfile(filename_temp_created, result_path)
                    os.unlink(filename_temp_created)
```
we avoid the delition of the temp file when the with clause is finished and we copy the file after, and we check if the filename exists first,

**Comment by pjonsson** [comment]
> .. inside the `with ... file:` the file is open in write mode, and since it' open in this mode the copyfile needs to read from the file but in windows specifically rise a permission error since it was open in write mode and not in read mode.

What you describe sounds like the bug I fixed in #164. Unfortunately we didn't get a crash on Linux, we got infrequently corrupted zip files instead.

**Comment by LattaruoloAndrea** [comment]
#164 should work on windows I tired and it worked

**Comment by LattaruoloAndrea** [comment]
@eikeschuett and @scotjohn there has been the new release that should fix the issue on windows if you guys can test it and it works we can close this issue

**Comment by pjonsson** [comment]
If it works for you @LattaruoloAndrea and nobody else has reacted/complained since Aug 2, I think we can close this issue as fixed.
