### ISSUE TITLE
Support for downloading Landsat?

### ISSUE THREAD

**Issue by pjonsson** [CDSETool/CDSETool#151]
## Summary

A lot of the machinery in CDSETool is quite generic and would look identical if re-implemented to target some other satellite image provider.

I'm not making any promises, but I happen to have some code for downloading some Landsat products, would that be of interest to CDSETool assuming it doesn't upset the overall architecture of CDSETool itself?

I realize Landsat is not in the scope of "CDSE", so if the scope extension of CDSETool is not wanted, this ticket can be closed.

**Comment by subnet001** [comment]
While i think the "spirit" of CDSETool has drifted towards being solely dedicated to CDSE, the original idea was to serve as a comprehensive followup to Sentinelsat, which had support for other platforms. 
I personally think the tool would make EO users lives easier, so i say go for it.

**Comment by pjonsson** [comment]
After I created this ticket, Copernicus has announced they are adding both Landsat (https://dataspace.copernicus.eu/news/2024-9-16-availability-landsat-data-copernicus-data-space-ecosystem-upcoming-changes) and Sentinel-3 OLCI (https://dataspace.copernicus.eu/news/2024-8-13-sentinel-3-olci-level-2-data-now-available-visualization-copernicus-browser-and) data.

I'm swamped for the rest of the year and the Landsat code I have is worse than CDSETool, so I think the best way forward is to make sure CDSETool works for downloading Landsat/Sentinel-3 OLCI from Copernicus servers. Since I'm not going to get around to bring in any additional Landsat support beyond that, I will close this ticket.

I don't think all Landsat products are provided by Copernicus, so if someone else wants to contribute code for getting them I assume they are welcome to do so.
