### ISSUE TITLE
Refactor .SAFE with .zip replacement

### ISSUE THREAD

**Issue by fbalaban** [CDSETool/CDSETool#180]
## Summary
In https://github.com/CDSETool/CDSETool/blob/main/src/cdsetool/download.py#L47
a replacement of .SAFE with .zip is performed. While this is true for e.g. Sentinel 2, it is not valid for Sentinel 3 (which "title" ends with SEN3).
Moreover, a simple refactor could be performed for not replacing .SAFE with .zip, but appending .zip in the end, in order to maintain uniformity with the Copernicus Browser download behavior, which maintains the .SAFE in the filename

### Motivation
Maintain uniformity along pipelines

**Comment by subnet001** [comment]
Thanks for reporting the bug and the fix. I personally only use Sentinel-1 and -2 data so this was a blindspot for me. I also appreciate the uniformity with the Copernicus browser. Thanks a lot!
