### ISSUE TITLE
Hanging download_feature because of 401/404 response

### ISSUE THREAD

**Issue by pjonsson** [CDSETool/CDSETool#84]
## Describe the bug
After some time downloading, the download hangs inside `download_feature`. I am not sure if the hang is deterministic, but it happens several times per week.

With #83 on top of main, here is a partial log with correct timestamps:
```
time=2024-02-25T04:59:48 level=INFO msg="Download started"
<614 successful downloads>
time=2024-02-25T13:02:48 level=INFO msg="Download started"
time=2024-02-25T13:02:49 level=WARNING msg="Status code 401, retrying.." file=download.py:109
time=2024-02-25T13:03:58 level=WARNING msg="Status code 401, retrying.." file=download.py:109
<loop continues with 401 status>
```
So it's hanging in the loop at https://github.com/SDFIdk/CDSETool/blob/8385e3a82d0915f472458955608ec40aadb0e082/src/cdsetool/download.py#L103

This is a different issue from #60 since that gives an exception.

### Steps to reproduce
Pseudo code for what produces the log:

```python
options = {... Credentials(user, password) ...}
for product in list_of_many_products:
    download_feature(product, options)
```

### Expected behavior
Some kind of recovery, or returning a failure, or throwing an exception.

### Environment
 - OS: Ubuntu 22.04
 - Package version: 0.2.3, but also CDSETool main branch with #83 on top.
 - Python version: 3.10

**Comment by pjonsson** [comment]
This happened again last night using main branch just before the proxy PR.
```
time=2024-03-07T22:27:51 level=INFO msg="Download started"
time=2024-03-07T22:27:52 level=WARNING msg="Status code 401, retrying.." file=download.py:104
time=2024-03-07T22:29:07 level=WARNING msg="Status code 401, retrying.." file=download.py:104
time=2024-03-07T22:30:08 level=WARNING msg="Status code 401, retrying.." file=download.py:104
```
@pedep a hanging job is a bit of an issue since that doesn't self-heal, any ideas?

**Comment by pjonsson** [comment]
I thought the monitor had something to do with things, but they always seem to be cleaned up properly for me.

**Comment by pedep** [comment]
I think i have an idea as to why the session will not refresh despite retrying for multiple seconds

```python
# [..snip..]
    with _get_monitor(options).status() as status:
        status.set_filename(filename)

        session = _get_credentials(options).get_session() # a session is acquired, which may be seconds from expiring
# [..snip..]
        response = _retry_backoff(url, session, options)
# [..snip..]

def _retry_backoff(url, session, options):
    response = session.get(url, stream=True) # by this point the session may already have gone bad
    # the while-loop contains no way of refreshing the session
    # so the stale access token is used indefinitely
    while response.status_code != 200:
        options["logger"].warning(f"Status code {response.status_code}, retrying..")
        time.sleep(60 * (1 + (random.random() / 4)))
        response = session.get(url, stream=True) 

    return response
```

**Comment by pjonsson** [comment]
Yes, hasn't that been obvious from the log in the issue?

**Comment by pedep** [comment]
Yes, thats what clued me in. I didnt have time to look at it until now.
If you knew that already, why spend time on a sidetrack like #100 ?

**Comment by pjonsson** [comment]
There are no comments in the code, but I assume there must have been a good reason to ignore every response code except 200 in the first place.

A hanging download requires a bunch of logic to monitor output and figure out if the python process should be killed, and killing the python process requires even further logic to restore other things to how they were before the download started, and then the python process needs to be started again. A download that returns a failure can be checked inside the python process and immediately retried, and the second download seems to work.

**Comment by pjonsson** [comment]
This morning I stopped getting 401 and started getting intermittent 404. It's possible that is just a disguised 401 that reveals less information, so I will check the logs next week and report back.

**Comment by pjonsson** [comment]
I have 404 and 500 in my logs now, so I guess they changed the response from 401 to 404.

**Comment by pjonsson** [comment]
This has been fixed for a long time.
